---
abstract: 'Check crontab format validity'
author:
  - 'Ryo Okamoto <ryo@aquahill.net>'
build_requires:
  Test::More: 0
  Test::Tester: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Crontab-Format
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Test::Crontab::Format:
    file: lib/Test/Crontab/Format.pm
    version: 0.02
requires:
  Parse::Crontab: 0.03
  perl: 5.008001
resources:
  bugtracker: https://github.com/ryochin/p5-test-crontab-format/issues
  homepage: https://github.com/ryochin/p5-test-crontab-format
  repository: git://github.com/ryochin/p5-test-crontab-format.git
version: 0.02
